### ISSUE TITLE
value支持渲染自定义标签吗？

### ISSUE THREAD

**Issue by rc558620** [ZhangTaoK/react-native-marquee-ab#1]
value支持渲染自定义标签吗？

**Comment by rc558620** [comment]
如果我要在里面加View或者img怎么弄呢

**Comment by ZhangTaoK** [comment]
@rc558620 暂时是不支持的，有时间的话我会去处理这部分功能。源码也比较简单，您可以自己试着改一下。

**Comment by ZhangTaoK** [comment]
@rc558620 v1.2.6  MarqueeVertical竖直滚动  增加headViews方法提供自定义标签的api
