### ISSUE TITLE
我使用MarqueeHorizontal 出现的问题

### ISSUE THREAD

**Issue by tumoxuese** [ZhangTaoK/react-native-marquee-ab#11]
我在首页使用MarqueeHorizontal ，发现跳转到其他页面的网络请求好像没有用了一样，redux的网络请求log 也不显示了，页面只能查看首页

**Comment by tumoxuese** [comment]
我好像知道什么原因了，我componentWillMount里面都写了InteractionManager.runAfterInteractions，首页的动画一直在滚动，然后其他页面就进不去，有什么好的解决办法吗

**Comment by ZhangTaoK** [comment]
抱歉，并不能很好的支持InteractionManager.runAfterInteractions
