### ISSUE TITLE
我现在提个需求，可否考虑实现一下

### ISSUE THREAD

**Issue by oMhuAaN** [ZhangTaoK/react-native-marquee-ab#12]
把现有的文字换成图片，任意多张图片滚动，
可否实现一下，谢谢。
最好同时支持手动滑动，即不碰的时候自动滚动，手放上去就停止不动，
手左右滑动，图片就跟着滑动，手放开，又开始自动滚动。
点击图片还可以跳转。

**Comment by ZhangTaoK** [comment]
这样可以直接使用swiper
https://github.com/leecade/react-native-swiper
