### ISSUE TITLE
从后台获取多条公告 ，轮播第一条后，会清空重播

### ISSUE THREAD

**Issue by moyrne** [ZhangTaoK/react-native-marquee-ab#17]
第一条清空重播后，后面的轮播正常 
希望大佬可以解决这个问题，已点赞！

**Comment by GHQEmperor** [comment]
解决办法: 在componentWillReceiveProps 中加一个判断值，当newText !== oldText 时，判断值为true（默认在state中是false）,因为这里的 newText 会执行几次，前几次都是textList都是[]，只有最后一次他才会等于你在组件外面传的值。  
然后你在最后渲染的地方改成 
`render(){
        let { width, height, bgContainerStyle } = this.props;
        let { textList,start } = this.state;
        return(
            <View style = {{
                ...styles.bgContainerStyle,
                width : width,
                height : height,
                ...bgContainerStyle,
            }} opacity = {this.state.animation ? 1 : 0}>
                {start&&this.textView(textList) }
                {start&&this.textLengthView(textList) }
            </View>
        )
    }`


修改后的代码是这样:
`import React, { Component } from 'react';
import { View, Animated, Easing, Text, TouchableOpacity, InteractionManager } from 'react-native';

const styles = {
    bgContainerStyle : {
        flexDirection : 'row',
        alignItems : 'center',
        justifyContent : 'flex-start',
        backgroundColor : '#FFFFFF',
        overflow : 'hidden'
    },
    textMeasuringViewStyle: {
        flexDirection : 'row',
        opacity : 0,
    },
    textMeasuringTextStyle: {
        fontSize : 16,
    },
    textStyle : {
        fontSize : 16,
        color : '#000000',
    }
};

export default class ScrollAnnounce extends Component {
    constructor(props) {
        super(props);
        this.state = {
            animation : null,
            textList : [],
            textWidth : 0,
            viewWidth : 0,
            start:false
        }
    }

    static defaultProps = {
        duration : 10000,
        speed : 0,
        textList : [],
        width : 375,
        height : 50,
        direction : 'left',
        reverse : false,
        separator : 20,
        onTextClick : () => {},
    }

    componentWillMount(){
        this.setState({
            textList : this.props.textList || [],
        })
        this.animatedTransformX = new Animated.Value(0);
    }

    componentDidUpdate(){
        let { textWidth, viewWidth } = this.state;
        let { duration, speed, width, direction } = this.props;
        let mDuration = duration;
        if(speed && speed > 0){
            mDuration = (width + textWidth) / speed * 1000;
        }
        if(!this.state.animation && textWidth && viewWidth){
            this.animatedTransformX.setValue(direction == 'left' ? width : (direction == 'right' ? -textWidth : width));
            this.setState({
                animation : Animated.timing(this.animatedTransformX, {
                    toValue: direction == 'left' ? -textWidth : (direction == 'right' ? width : -textWidth),
                    duration: mDuration,
                    useNativeDriver: true,
                    easing: Easing.linear,
                }),
            }, () => {
                this.state.animation && this.state.animation.start(() => {
                    this.setState({
                        animation: null,
                    });
                });
            })
        }
     
    }

 


    componentWillReceiveProps(nextProps){
        let newText = nextProps.textList || [];
        let oldText = this.props.textList || [];
        if (newText !== oldText) {
            this.state.animation && this.state.animation.stop();
            this.setState({
                textList : newText,
                animation: null,
                start:true
            });
        }
    }

    componentWillUnmount(){
        this.state.animation && this.state.animation.stop();
    }

    textOnLayout = (e) => {
        let width = e.nativeEvent.layout.width;
        let { textList, separator } = this.props;
        this.setState({
            textWidth : width + ((textList.length - 1) * separator),
        })
    }

    viewOnLayout = (e) => {
        let width = e.nativeEvent.layout.width;
        this.setState({
            viewWidth : width,
        })
    }

    textView(list){
        let { textStyle, onTextClick, reverse, separator } = this.props;
        let itemView = [];
        for(let i = 0;i<list.length;i++){
            let item = list[i];
            if(reverse){
                item.value = item.value.split("").reverse().join("");
            }
            itemView.push(
                <TouchableOpacity key = {''+i} activeOpacity = {0.9} onPress = {() => {
                    onTextClick(item)
                }}>
                    <View style = {{flexDirection : 'row',marginRight : i < list.length - 1 ? separator : 0}}>
                        <Text style = {{
                            ...styles.textStyle,
                            ...textStyle
                        }}
                              numberOfLines = {1}
                        >{item.value}</Text>
                    </View>
                </TouchableOpacity>
            );
        }
        return(
            <Animated.View
                style = {{flexDirection : 'row',width : this.state.textWidth,transform: [{ translateX: this.animatedTransformX }]}}
                onLayout={(event) => this.viewOnLayout(event)}
            >
                {itemView}
            </Animated.View>
        )

    }

    textLengthView(list){
        let { textStyle } = this.props;
        let text = '';
        for(let i = 0;i<list.length;i++){
            text += list[i].value;
        }
        return(
            <View style = {{
                ...styles.textMeasuringViewStyle,
                width : list.length * 1024
            }}>
                <Text style = {{
                    ...styles.textMeasuringTextStyle,
                    ...textStyle
                }}
                      onLayout={(event) => this.textOnLayout(event)}
                      numberOfLines = {1}
                >{text}</Text>
            </View>
        )

    }

    render(){
        let { width, height, bgContainerStyle } = this.props;
        let { textList,start } = this.state;
        return(
            <View style = {{
                ...styles.bgContainerStyle,
                width : width,
                height : height,
                ...bgContainerStyle,
            }} opacity = {this.state.animation ? 1 : 0}>
                {start&&this.textView(textList) }
                {start&&this.textLengthView(textList) }
            </View>
        )

    }
}
`

**Comment by ZhangTaoK** [comment]
感谢
