### ISSUE TITLE
影响其他View的显示？

### ISSUE THREAD

**Issue by pandrawla** [ZhangTaoK/react-native-marquee-ab#2]
用了之后我的banner轮播不显示了，SectionList显示部分数据，什么原因？注释掉该组件就好了

**Comment by ZhangTaoK** [comment]
@pandrawla 麻烦贴出您的全部代码。

**Comment by ZhangTaoK** [comment]
@pandrawla https://github.com/ZhangTaoK/react-native-marquee-ab/blob/master/README.md 您是否完全按照事例去实现的代码？

**Comment by pandrawla** [comment]
> @pandrawla 麻烦贴出您的全部代码。
能加下你QQ吗？

**Comment by pandrawla** [comment]
能加下你QQ吗？我的1067818152
代码
let notifyView = null;
if (this.state.notify && this.state.notify.length > 0) {
this.state.notify.forEach((item,index)=>{
item.value = item.title;
});
notifyView = <MarqueeVertical
textList = {this.state.notify}
width = {screenWidth-100}
height = {40}
direction = {'up'}
numberOfLines = {1}
textStyle = {{fontSize : 13,color : '#222222'}}
onTextClick = {(item) => {
this.props.navigation.navigate('NotifyDetails',{title:'公告',notifyId:item.id});
}}/>;
// notifyView = null;
}
下面调用{notifyView}
功能正常着，就是加上这个我的banner不显示了，sectionList只显示一部分
