### ISSUE TITLE
点击弹出框样式自定义

### ISSUE THREAD

**Issue by guopingApple** [ZhangTaoK/react-native-marquee-ab#20]
onTextClick (fun) 点击事件回调 : 返回点击的textList中的item

弹出框可以是自定义的界面吗？

onTextClick={item => {
                      // alert('' + JSON.stringify(item.noteContent));
                      return (
                        <View>
                          <Text>aaaa</Text>
                          <View>bbbbb</View>
                        </View>
                      );
                    }}

**Comment by ZhangTaoK** [comment]
@guopingApple 这里只是一个回调，您可以在方法体里编写任意代码。
