### ISSUE TITLE
横向跑马灯显示不全问题

### ISSUE THREAD

**Issue by a728384698** [ZhangTaoK/react-native-marquee-ab#21]
![截屏2020-01-07上午11 43 43](https://user-images.githubusercontent.com/7380874/71867147-e2735300-3143-11ea-9ee7-93358542422d.png)

因滚动文本长度相差较大，经常等待下一次开始时间比较长，修改成上图那样

问题：
我有三条比较长的数据 正常滚动可以，删除一条刷新，第一次还是按3条滚动的距离2条滚完之后有空白期（之前第三条的长度），等待时间比较长
 我要是有2条数据 新增一条，第一次也是以2条数据的滚动距离，第三条距离不足 还没滚完 直接开始下次滚动.
textWidth的宽度是以文本长度来计算的，有以上问题 我textWidth 的宽度是有改变的正确的，但是实际滚动还是 上一次的距离。

**Comment by ZhangTaoK** [comment]
@a728384698  你好，请贴出详细代码。

**Comment by a728384698** [comment]
@ZhangTaoK 
export default class MarqueeHorizontal extends Component {
  constructor(props) {
    super(props)
    this.state = {
      animation: null,
      textList: [],
      textWidth: 0,
      viewWidth: 0
    }
  }

  static defaultProps = {
    duration: 20000,
    speed: 0,
    textList: [],
    width: deviceDpWidth * 0.7,
    height: 50,
    direction: 'left',
    reverse: false,
    separator: deviceDpWidth * 0.4,  ==> 修改
    onTextClick: () => {}
  }

  componentWillMount() {
    this.setState({
      textList: this.props.textList || []
    })
    this.animatedTransformX = new Animated.Value(0)
  }

  componentDidUpdate() {
    let { textWidth, viewWidth } = this.state
    let { duration, speed, width, direction } = this.props
    let mDuration = duration
    if (speed && speed > 0) {
      mDuration = ((width + textWidth) / speed) * 1000
    }
    if (!this.state.animation && textWidth && viewWidth) {
      this.animatedTransformX.setValue(
        direction == 'left' ? width : direction == 'right' ? -textWidth : width
      )
      this.setState(
        {
          animation: Animated.timing(this.animatedTransformX, {
            toValue:
              direction == 'left'
                ? -textWidth
                : direction == 'right'
                ? width
                : -textWidth,
            duration: mDuration,
            useNativeDriver: true,
            easing: Easing.linear
          })
        },
        () => {
          this.state.animation &&
            this.state.animation.start(() => {
              this.setState({
                animation: null
              })
            })
        }
      )
    }
  }

  componentWillReceiveProps(nextProps) {
    let newText = nextProps.textList || []
    let oldText = this.state.textList || []
    if (newText.sort().toString() !== oldText.sort().toString()) {
      this.state.animation && this.state.animation.stop()
      this.setState({
        textList: newText,
        animation: null
      })
      return
    } else {
      newText.length > 0 &&
        newText.map((info, index) => {
          if (!isObjEqual(info, oldText[index])) {
            this.state.animation && this.state.animation.stop()  ==> 这块只是内容比较
            this.setState({
              textList: newText,
              animation: null
            })
          }
        })
    }
  }

  componentWillUnmount() {
    this.state.animation && this.state.animation.stop()
  }

  textOnLayout = e => {
    let width = e.nativeEvent.layout.width
    let { textList, separator } = this.props
    let len = textList.length == 1 ? textList.length : textList.length - 1
    this.setState({
      textWidth: width //+ len * separator //textList.length - 1 ==> 修改
    })
  }

  viewOnLayout = e => {
    let width = e.nativeEvent.layout.width
    this.setState({

      viewWidth: width    

    })
  }

  textView(list) {
    let { textStyle, onTextClick, reverse, separator, height } = this.props
    let itemView = []
    for (let i = 0; i < list.length; i++) {
      let item = list[i]
      if (reverse) {
        // item.value = item.value
        item.desc = item.desc
          .split('')
          .reverse()
          .join('')
      }
      itemView.push(
        <TouchableOpacity
          key={'' + i}
          activeOpacity={0.9}
          onPress={() => {
            onTextClick(item)
          }}
          style={{
            height: height,
            justifyContent: 'center'
          }}
        >
          <View
            style={{
              flexDirection: 'row',
              marginRight: i < list.length - 1 ? separator : 0
            }}
          >
            <Text
              style={{
                ...styles.textStyle,
                ...textStyle
              }}
              numberOfLines={1}
            >
              {item.desc}
            </Text>
          </View>
        </TouchableOpacity>
      )
    }
    return (
      <Animated.View
        style={{
          flexDirection: 'row',
          width: this.state.textWidth,
          transform: [{ translateX: this.animatedTransformX }]
        }}
        onLayout={event => this.viewOnLayout(event)}
      >
        {itemView}
      </Animated.View>
    )
  }

  textLengthView(list) {
    let { textStyle } = this.props
    let text = ''
    for (let i = 0; i < list.length; i++) {
      text += list[i].desc
      //   text += list[i].value
    }
    return (
      <View
        style={{
          ...styles.textMeasuringViewStyle,
          width: list.length * 1024
        }}
      >
        <Text
          style={{
            ...styles.textMeasuringTextStyle,
            ...textStyle
          }}
          onLayout={event => this.textOnLayout(event)}
          numberOfLines={1}
        >
          {text}
        </Text>
      </View>
    )
  }

  render() {
    let { width, height, bgContainerStyle } = this.props
    let { textList } = this.state
    return (
      <View
        style={{
          ...styles.bgContainerStyle,
          width: width,
          height: height,
          ...bgContainerStyle
        }}
        opacity={this.state.animation ? 1 : 0}
      >
        {this.textView(textList)}
        {this.textLengthView(textList)}
      </View>
    )
  }
}

我这边只是copy了MarqueeHorizontal.js 中的代码 ，用原文件代码试了一下 也是有相同问题。
似乎是我下拉刷新完 textWidth 还没计算出来componentDidUpdate就已经执行了(这时候textwidth，viewWidth的值是上次的) 等到textWIdth计算出之后本次正在使用的就是上一次计算的textwidth

**Comment by ZhangTaoK** [comment]
可以临时修改源码（width: list.length * 1024）  “1024”是每一条数据的最大长度，可以临时修改这个数值来解决这个问题，但相应的可能会造成卡顿。我在下一版本将会处理这个问题。

**Comment by zzq22406** [comment]
请问解决了吗？
