### ISSUE TITLE
能否让 backgroundColor可以自行修改，来更好地兼容夜间模式

### ISSUE THREAD

**Issue by Lylisa** [ZhangTaoK/react-native-marquee-ab#29]
您好，我看目前控件的 backgroundColor : '#FFFFFF',是写死的不能修改，app如果兼容夜间模式的话，这个背景还是白色不能修改，麻烦您在最新的版本中把 backgroundColor 这个属性以及背景的样式，还有文字的样式提供出来让我们可以自行定义，非常感谢

**Comment by ZhangTaoK** [comment]
文档中已注明：bgContainerStyle可以对背景进行修改。

**Comment by Lylisa** [comment]
好的，非常感谢，问题已经解决，神速的回复，谢谢大神
